document.writeln("	<footer class=\'footer-section spad set-bg\' data-setbg=\'img/footer-bg.svg\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'row\'>");
document.writeln("						<!-- contact info -->");
document.writeln("						<div class=\'col-sm-4 cont-info wow fadeInUp\' data-wow-delay=\'0.2s\'>");
document.writeln("							<i class=\'ti-email\'></i>");
document.writeln("							<span>yifeigong2020@u.northwstern.edu</span>");
document.writeln("							<p>email</p>");
document.writeln("						</div>");
document.writeln("						<!-- contact info -->");
document.writeln("						<div class=\'col-sm-4 cont-info wow fadeInUp\' data-wow-delay=\'0.4s\'>");
document.writeln("							<i class=\'ti-linkedin\'></i>");
document.writeln("							<a href=\'https://www.linkedin.com/in/yfgong/\' target=\'_blank\'>Faye Yifei Gong</a>");
document.writeln("							<p>Linkedin</p>");
document.writeln("						</div>");
document.writeln("						<!-- contact info -->");
document.writeln("						<div class=\'col-sm-4 cont-info wow fadeInUp\' data-wow-delay=\'0.6s\'>");
document.writeln("							<i class=\'ti-mobile\'></i>");
document.writeln("							<span>224-420-1511</span>");
document.writeln("							<p>Phone</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("			<!-- copyright -->");
document.writeln("			<p class=\'copyright\'>©Copyright yifeigong.top All rights reserved.</p>");
document.writeln("		</div>");
document.writeln("	</footer>");