document.writeln("<header class=\'header-section\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'header-warp\'>");
document.writeln("				<!-- Site Logo -->");
document.writeln("				<a href=\'index.html\' class=\'site-logo\'>");
document.writeln("					<img src=\'img/logo.png\' alt=\'\'>");
document.writeln("				</a>");
document.writeln("				<!-- Site Menu -->");
document.writeln("				<div class=\'responsive-switch\'><i class=\'fa fa-bars\'></i></div>");
document.writeln("				<nav class=\'site-menu\'>");
document.writeln("					<div class=\'sm-close\'><i class=\'ti-close\'></i></div>");
document.writeln("					<ul class=\'menu-list\'>");
document.writeln("						<li><a href=\'index.html\'>Home</a></li>");
document.writeln("						<li><a href=\'work.html\'>Work</a></li>");
document.writeln("						<li><a href=\'aboutme.html\'>About Me</a></li>");
document.writeln("						<li><a href=\'yifeigong.pdf\' target=\'_blank\'>Résumé</a></li>");
document.writeln("					</ul>");
document.writeln("				</nav>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</header>");